language: php
cache:
  directories:
    - $COMPOSER_CACHE_DIR
    - vendor
install:
  - 'composer install --no-scripts'
php:
  - '5.4'
  - '5.5'
  - '5.6'
script: 
  - 'find . -type f -iname "*.php" -not -path "./lib/quail/tests/*" -not -path "./vendor/*" | xargs -n1 php -l'
  - './vendor/phpunit/phpunit/phpunit --testsuite "UDOIT"'
